import { defineConfig, envField, fontProviders } from "astro/config";
import tailwindcss from "@tailwindcss/vite";
import sitemap from "@astrojs/sitemap";
import remarkToc from "remark-toc";
import remarkCollapse from "remark-collapse";
import { remarkReadingTime } from "./src/utils/remarkReadingTime";
import {
  transformerNotationDiff,
  transformerNotationHighlight,
  transformerNotationWordHighlight,
} from "@shikijs/transformers";
import { transformerFileName } from "./src/utils/transformers/fileName";
import { SITE } from "./src/config";

// https://astro.build/config
export default defineConfig({
  site: SITE.website,
  redirects: {
    // Old Zola URLs without date prefix → current Astro URLs with date prefix
    // Pattern: /posts/slug/ → /posts/YYYY-MM-DD-slug/
    "/posts/moved-and-lost/": "/posts/2009-08-01-moved-and-lost/",
    "/posts/web-application-tools/": "/posts/2009-08-03-web-application-tools/",
    "/posts/redmine-on-ubuntu-9-dot-04-with-nginx/": "/posts/2009-08-17-redmine-on-ubuntu-9-dot-04-with-nginx/",
    "/posts/ubuntu-server-maintenance/": "/posts/2009-08-18-ubuntu-server-maintenance/",
    "/posts/message-driven-beans/": "/posts/2010-02-05-message-driven-beans/",
    "/posts/java-persistence-api/": "/posts/2010-02-10-java-persistence-api/",
    "/posts/ejb-concepts-and-services/": "/posts/2010-02-16-ejb-concepts-and-services/",
    "/posts/renaming-files/": "/posts/2010-05-09-renaming-files/",
    "/posts/gsoc-2010-testing/": "/posts/2010-05-24-gsoc-2010-testing/",
    "/posts/mynet/": "/posts/2010-06-05-mynet/",
    "/posts/im-from-barcelona/": "/posts/2010-07-02-im-from-barcelona/",
    "/posts/sonar-and-hudson/": "/posts/2010-07-04-sonar-and-hudson/",
    "/posts/how-to-heal-and-prevent-computer-injury-rsi/": "/posts/2010-07-10-how-to-heal-and-prevent-computer-injury-rsi/",
    "/posts/estatut-de-catalunya-a-review/": "/posts/2010-07-12-estatut-de-catalunya-a-review/",
    "/posts/java-vector-is-obsolete/": "/posts/2010-08-08-java-vector-is-obsolete/",
    "/posts/gsoc-2010/": "/posts/2010-10-06-gsoc-2010/",
    "/posts/java-7-whats-new/": "/posts/2011-07-14-java-7-whats-new/",
    "/posts/scala-move-forward/": "/posts/2011-07-19-scala-move-forward/",
    "/posts/its-back/": "/posts/2012-06-17-its-back/",
    "/posts/responsive-design-and-mobile-first/": "/posts/2012-07-22-responsive-design-and-mobile-first/",
    "/posts/learning-scala-in-coursera/": "/posts/2012-10-15-learning-scala-in-coursera/",
    "/posts/iteratees-and-play-2/": "/posts/2012-11-18-iteratees-and-play-2/",
    "/posts/executing-jasmine-tests-in-play-2-dot-0-4/": "/posts/2013-01-26-executing-jasmine-tests-in-play-2-dot-0-4/",
    "/posts/using-redis-pubsub-with-play-2-dot-1-0/": "/posts/2013-02-24-using-redis-pubsub-with-play-2-dot-1-0/",
    "/posts/using-ansible-to-deploy-play-framework-apps-in-ec2-instances/": "/posts/2013-04-01-using-ansible-to-deploy-play-framework-apps-in-ec2-instances/",
    "/posts/scala-in-2018/": "/posts/2013-08-25-scala-in-2018/",
    "/posts/breaking-the-1000ms-time-to-glass-mobile-barrier/": "/posts/2013-08-26-breaking-the-1000ms-time-to-glass-mobile-barrier/",
    "/posts/enums-to-json-in-scala/": "/posts/2013-09-21-enums-to-json-in-scala/",
    "/posts/on-learn-startup-and-personal-waste/": "/posts/2013-10-20-on-learn-startup-and-personal-waste/",
    "/posts/gumtree-blog-is-live/": "/posts/2013-12-15-gumtree-blog-is-live/",
    "/posts/twilio-and-play-framework/": "/posts/2014-01-10-twilio-and-play-framework/",
    "/posts/raspberry-pi-as-nas-with-samba/": "/posts/2014-01-12-raspberry-pi-as-nas-with-samba/",
    "/posts/builder-pattern-and-inheritance-in-java/": "/posts/2014-02-23-builder-pattern-and-inheritance-in-java/",
    "/posts/java-8-is-coming/": "/posts/2014-03-08-java-8-is-coming/",
    "/posts/reactconf-and-orm-future/": "/posts/2014-04-13-reactconf-and-orm-future/",
    "/posts/meetup-building-a-developer-centred-company-culture/": "/posts/2014-06-21-meetup-building-a-developer-centred-company-culture/",
    "/posts/hystrix-at-gumtree/": "/posts/2015-01-07-hystrix-at-gumtree/",
    "/posts/real-time-analytics-with-apache-storm-at-udacity/": "/posts/2015-02-01-real-time-analytics-with-apache-storm-at-udacity/",
    "/posts/mining-massive-datasets/": "/posts/2015-02-05-mining-massive-datasets/",
    "/posts/machine-learning-at-coursera/": "/posts/2015-02-08-machine-learning-at-coursera/",
    "/posts/game-development-using-unity3d/": "/posts/2015-02-15-game-development-using-unity3d/",
    "/posts/real-time-analytics-with-storm-lesson-2/": "/posts/2015-02-15-real-time-analytics-with-storm-lesson-2/",
    "/posts/real-time-analytics-with-apache-storm-done/": "/posts/2015-02-22-real-time-analytics-with-apache-storm-done/",
    "/posts/qcon-london-microservices/": "/posts/2015-03-07-qcon-london-microservices/",
    "/posts/wearables-google-vs-apple/": "/posts/2015-05-04-wearables-google-vs-apple/",
    "/posts/using-docker-in-heroku/": "/posts/2015-05-11-using-docker-in-heroku/",
    "/posts/scala-repl/": "/posts/2015-07-03-scala-repl/",
    "/posts/emacs-and-scala-in-mac-os-x-yosemite/": "/posts/2015-09-20-emacs-and-scala-in-mac-os-x-yosemite/",
    "/posts/scala-exchange-2015-day-one/": "/posts/2015-12-10-scala-exchange-2015-day-one/",
    "/posts/scala-exchange-2015-day-two/": "/posts/2015-12-11-scala-exchange-2015-day-two/",
    "/posts/monkey-island-battles-and-webkit/": "/posts/2016-03-25-monkey-island-battles-and-webkit/",
    "/posts/understanding-free-monads/": "/posts/2016-05-28-understanding-free-monads/",
    "/posts/freek-and-free-monads/": "/posts/2016-05-30-freek-and-free-monads/",
    "/posts/free-monads-and-stockfighter/": "/posts/2016-08-22-free-monads-and-stockfighter/",
    "/posts/learning-shapeless/": "/posts/2016-11-14-learning-shapeless/",
    "/posts/finch-underscore-post/": "/posts/2017-01-25-finch-underscore-post/",
    "/posts/refining-your-data/": "/posts/2017-03-09-refining-your-data/",
    "/posts/tips-working-fs2/": "/posts/2018-03-20-tips-working-fs2/",
    "/posts/bridges/": "/posts/2018-12-28-bridges/",
    "/posts/playing-with-rust/": "/posts/2019-02-05-playing-with-rust/",
    "/posts/webassembly-rust-edge-computing/": "/posts/2019-05-07-webassembly-rust-edge-computing/",
    "/posts/remote-build-servers-with-vs-code-and-metals/": "/posts/2020-05-08-remote-build-servers-with-vs-code-and-metals/",
    "/posts/shadow-it-chaordic/": "/posts/2022-12-04-shadow-it-chaordic/",
    "/posts/gpt-replace-software-engineers/": "/posts/2023-01-24-gpt-replace-software-engineers/",
    "/posts/scala-steward-automerge/": "/posts/2023-01-28-scala-steward-automerge/",
    "/posts/wardley-maps-stop-waste/": "/posts/2023-03-02-wardley-maps-stop-waste/",
    "/posts/yes-code-ai-no-code/": "/posts/2023-04-25-yes-code-ai-no-code/",
    "/posts/is-your-llm-use-compliant/": "/posts/2023-07-05-is-your-llm-use-compliant/",
    "/posts/running-llm-on-your-own/": "/posts/2023-09-15-running-llm-on-your-own/",
    "/posts/understanding-data-mesh/": "/posts/2023-11-10-understanding-data-mesh/",
    "/posts/cloud-exit-mirage-aws-alternatives/": "/posts/2024-11-12-cloud-exit-mirage-aws-alternatives/",
    "/posts/durable-computing-hype/": "/posts/2024-12-27-durable-computing-hype/",
    "/posts/year-orchestrators-talk/": "/posts/2026-02-02-year-orchestrators-talk/",
    "/posts/give-claude-chrome-cli-superpowers/": "/posts/2026-02-10-give-claude-chrome-cli-superpowers/",
    "/posts/are-llm-killing-oss/": "/posts/2026-02-13-are-llm-killing-oss/",
    "/posts/meme-agent-leverage-gap/": "/posts/2026-02-18-meme-agent-leverage-gap/",
    "/posts/llms-are-monkey-paws/": "/posts/2026-02-24-llms-are-monkey-paws/",
    "/posts/ai-sandbox-coding-agents/": "/posts/2026-03-03-ai-sandbox-coding-agents/",
    "/posts/llms-are-already-useful/": "/posts/2026-03-06-llms-are-already-useful/",
    "/posts/fulcrums-of-ai-developer-evolution/": "/posts/2026-03-15-fulcrums-of-ai-developer-evolution/",
    "/posts/code-is-cheap-now/": "/posts/2026-03-16-code-is-cheap-now/",
    "/posts/ai-is-an-exoskeleton-not-a-coworker/": "/posts/2026-03-17-ai-is-an-exoskeleton-not-a-coworker/",
    "/posts/your-first-day-with-claude-code/": "/posts/2026-03-18-your-first-day-with-claude-code/",
    "/posts/the-one-file-that-makes-or-breaks-your-ai-workflow/": "/posts/2026-03-23-the-one-file-that-makes-or-breaks-your-ai-workflow/",
    "/posts/building-agent-memory-that-survives-between-sessions/": "/posts/2026-03-24-building-agent-memory-that-survives-between-sessions/",
    // Old root-level Zola URLs → current Astro URLs
    // Pattern: /slug/ → /posts/YYYY-MM-DD-slug/
    "/moved-and-lost/": "/posts/2009-08-01-moved-and-lost/",
    "/web-application-tools/": "/posts/2009-08-03-web-application-tools/",
    "/redmine-on-ubuntu-9-dot-04-with-nginx/": "/posts/2009-08-17-redmine-on-ubuntu-9-dot-04-with-nginx/",
    "/ubuntu-server-maintenance/": "/posts/2009-08-18-ubuntu-server-maintenance/",
    "/message-driven-beans/": "/posts/2010-02-05-message-driven-beans/",
    "/java-persistence-api/": "/posts/2010-02-10-java-persistence-api/",
    "/ejb-concepts-and-services/": "/posts/2010-02-16-ejb-concepts-and-services/",
    "/renaming-files/": "/posts/2010-05-09-renaming-files/",
    "/gsoc-2010-testing/": "/posts/2010-05-24-gsoc-2010-testing/",
    "/mynet/": "/posts/2010-06-05-mynet/",
    "/im-from-barcelona/": "/posts/2010-07-02-im-from-barcelona/",
    "/sonar-and-hudson/": "/posts/2010-07-04-sonar-and-hudson/",
    "/how-to-heal-and-prevent-computer-injury-rsi/": "/posts/2010-07-10-how-to-heal-and-prevent-computer-injury-rsi/",
    "/estatut-de-catalunya-a-review/": "/posts/2010-07-12-estatut-de-catalunya-a-review/",
    "/java-vector-is-obsolete/": "/posts/2010-08-08-java-vector-is-obsolete/",
    "/gsoc-2010/": "/posts/2010-10-06-gsoc-2010/",
    "/java-7-whats-new/": "/posts/2011-07-14-java-7-whats-new/",
    "/scala-move-forward/": "/posts/2011-07-19-scala-move-forward/",
    "/its-back/": "/posts/2012-06-17-its-back/",
    "/responsive-design-and-mobile-first/": "/posts/2012-07-22-responsive-design-and-mobile-first/",
    "/learning-scala-in-coursera/": "/posts/2012-10-15-learning-scala-in-coursera/",
    "/iteratees-and-play-2/": "/posts/2012-11-18-iteratees-and-play-2/",
    "/executing-jasmine-tests-in-play-2-dot-0-4/": "/posts/2013-01-26-executing-jasmine-tests-in-play-2-dot-0-4/",
    "/using-redis-pubsub-with-play-2-dot-1-0/": "/posts/2013-02-24-using-redis-pubsub-with-play-2-dot-1-0/",
    "/using-ansible-to-deploy-play-framework-apps-in-ec2-instances/": "/posts/2013-04-01-using-ansible-to-deploy-play-framework-apps-in-ec2-instances/",
    "/scala-in-2018/": "/posts/2013-08-25-scala-in-2018/",
    "/breaking-the-1000ms-time-to-glass-mobile-barrier/": "/posts/2013-08-26-breaking-the-1000ms-time-to-glass-mobile-barrier/",
    "/enums-to-json-in-scala/": "/posts/2013-09-21-enums-to-json-in-scala/",
    "/on-learn-startup-and-personal-waste/": "/posts/2013-10-20-on-learn-startup-and-personal-waste/",
    "/gumtree-blog-is-live/": "/posts/2013-12-15-gumtree-blog-is-live/",
    "/twilio-and-play-framework/": "/posts/2014-01-10-twilio-and-play-framework/",
    "/raspberry-pi-as-nas-with-samba/": "/posts/2014-01-12-raspberry-pi-as-nas-with-samba/",
    "/builder-pattern-and-inheritance-in-java/": "/posts/2014-02-23-builder-pattern-and-inheritance-in-java/",
    "/java-8-is-coming/": "/posts/2014-03-08-java-8-is-coming/",
    "/reactconf-and-orm-future/": "/posts/2014-04-13-reactconf-and-orm-future/",
    "/meetup-building-a-developer-centred-company-culture/": "/posts/2014-06-21-meetup-building-a-developer-centred-company-culture/",
    "/hystrix-at-gumtree/": "/posts/2015-01-07-hystrix-at-gumtree/",
    "/real-time-analytics-with-apache-storm-at-udacity/": "/posts/2015-02-01-real-time-analytics-with-apache-storm-at-udacity/",
    "/mining-massive-datasets/": "/posts/2015-02-05-mining-massive-datasets/",
    "/machine-learning-at-coursera/": "/posts/2015-02-08-machine-learning-at-coursera/",
    "/game-development-using-unity3d/": "/posts/2015-02-15-game-development-using-unity3d/",
    "/real-time-analytics-with-storm-lesson-2/": "/posts/2015-02-15-real-time-analytics-with-storm-lesson-2/",
    "/real-time-analytics-with-apache-storm-done/": "/posts/2015-02-22-real-time-analytics-with-apache-storm-done/",
    "/qcon-london-microservices/": "/posts/2015-03-07-qcon-london-microservices/",
    "/wearables-google-vs-apple/": "/posts/2015-05-04-wearables-google-vs-apple/",
    "/using-docker-in-heroku/": "/posts/2015-05-11-using-docker-in-heroku/",
    "/scala-repl/": "/posts/2015-07-03-scala-repl/",
    "/emacs-and-scala-in-mac-os-x-yosemite/": "/posts/2015-09-20-emacs-and-scala-in-mac-os-x-yosemite/",
    "/scala-exchange-2015-day-one/": "/posts/2015-12-10-scala-exchange-2015-day-one/",
    "/scala-exchange-2015-day-two/": "/posts/2015-12-11-scala-exchange-2015-day-two/",
    "/monkey-island-battles-and-webkit/": "/posts/2016-03-25-monkey-island-battles-and-webkit/",
    "/understanding-free-monads/": "/posts/2016-05-28-understanding-free-monads/",
    "/freek-and-free-monads/": "/posts/2016-05-30-freek-and-free-monads/",
    "/free-monads-and-stockfighter/": "/posts/2016-08-22-free-monads-and-stockfighter/",
    "/learning-shapeless/": "/posts/2016-11-14-learning-shapeless/",
    "/finch-underscore-post/": "/posts/2017-01-25-finch-underscore-post/",
    "/refining-your-data/": "/posts/2017-03-09-refining-your-data/",
    "/tips-working-fs2/": "/posts/2018-03-20-tips-working-fs2/",
    "/bridges/": "/posts/2018-12-28-bridges/",
    "/playing-with-rust/": "/posts/2019-02-05-playing-with-rust/",
    "/webassembly-rust-edge-computing/": "/posts/2019-05-07-webassembly-rust-edge-computing/",
    "/remote-build-servers-with-vs-code-and-metals/": "/posts/2020-05-08-remote-build-servers-with-vs-code-and-metals/",
    "/shadow-it-chaordic/": "/posts/2022-12-04-shadow-it-chaordic/",
    "/gpt-replace-software-engineers/": "/posts/2023-01-24-gpt-replace-software-engineers/",
    "/scala-steward-automerge/": "/posts/2023-01-28-scala-steward-automerge/",
    "/wardley-maps-stop-waste/": "/posts/2023-03-02-wardley-maps-stop-waste/",
    "/yes-code-ai-no-code/": "/posts/2023-04-25-yes-code-ai-no-code/",
    "/is-your-llm-use-compliant/": "/posts/2023-07-05-is-your-llm-use-compliant/",
    "/running-llm-on-your-own/": "/posts/2023-09-15-running-llm-on-your-own/",
    "/understanding-data-mesh/": "/posts/2023-11-10-understanding-data-mesh/",
    "/cloud-exit-mirage-aws-alternatives/": "/posts/2024-11-12-cloud-exit-mirage-aws-alternatives/",
    "/durable-computing-hype/": "/posts/2024-12-27-durable-computing-hype/",
    "/year-orchestrators-talk/": "/posts/2026-02-02-year-orchestrators-talk/",
    "/give-claude-chrome-cli-superpowers/": "/posts/2026-02-10-give-claude-chrome-cli-superpowers/",
    "/are-llm-killing-oss/": "/posts/2026-02-13-are-llm-killing-oss/",
    "/meme-agent-leverage-gap/": "/posts/2026-02-18-meme-agent-leverage-gap/",
    "/llms-are-monkey-paws/": "/posts/2026-02-24-llms-are-monkey-paws/",
    "/ai-sandbox-coding-agents/": "/posts/2026-03-03-ai-sandbox-coding-agents/",
    "/llms-are-already-useful/": "/posts/2026-03-06-llms-are-already-useful/",
    "/fulcrums-of-ai-developer-evolution/": "/posts/2026-03-15-fulcrums-of-ai-developer-evolution/",
    "/code-is-cheap-now/": "/posts/2026-03-16-code-is-cheap-now/",
    "/ai-is-an-exoskeleton-not-a-coworker/": "/posts/2026-03-17-ai-is-an-exoskeleton-not-a-coworker/",
    "/your-first-day-with-claude-code/": "/posts/2026-03-18-your-first-day-with-claude-code/",
    "/the-one-file-that-makes-or-breaks-your-ai-workflow/": "/posts/2026-03-23-the-one-file-that-makes-or-breaks-your-ai-workflow/",
    "/building-agent-memory-that-survives-between-sessions/": "/posts/2026-03-24-building-agent-memory-that-survives-between-sessions/",
  },
  integrations: [
    sitemap({
      filter: page => SITE.showArchives || !page.endsWith("/archives"),
    }),
  ],
  markdown: {
    remarkPlugins: [
      remarkToc,
      [remarkCollapse, { test: "Table of contents" }],
      remarkReadingTime,
    ],
    shikiConfig: {
      // For more themes, visit https://shiki.style/themes
      themes: { light: "github-light", dark: "github-dark" },
      defaultColor: false,
      wrap: true,
      transformers: [
        transformerFileName({ style: "v2", hideDot: false }),
        transformerNotationHighlight(),
        transformerNotationWordHighlight(),
        transformerNotationDiff({ matchAlgorithm: "v3" }),
      ],
    },
  },
  vite: {
    // eslint-disable-next-line
    // @ts-ignore
    // This will be fixed in Astro 6 with Vite 7 support
    // See: https://github.com/withastro/astro/issues/14030
    plugins: [tailwindcss()],
    optimizeDeps: {
      exclude: ["@resvg/resvg-js"],
    },
  },
  image: {
    responsiveStyles: true,
    layout: "constrained",
  },
  env: {
    schema: {
      PUBLIC_GOOGLE_SITE_VERIFICATION: envField.string({
        access: "public",
        context: "client",
        optional: true,
      }),
    },
  },
  experimental: {
    preserveScriptOrder: true,
    fonts: [
      {
        name: "Google Sans Code",
        cssVariable: "--font-google-sans-code",
        provider: fontProviders.google(),
        fallbacks: ["monospace"],
        weights: [300, 400, 500, 600, 700],
        styles: ["normal", "italic"],
      },
    ],
  },
});
